version: "3"
services:
  nodecook-agent:
    image: nodecook-agent
    build: .
    container_name: nodecook-agent
    restart: always
    network_mode: host
    user: root
    environment:
      - NCA_API_KEY=${NCA_API_KEY}
